#!/bin/sh

THISDIR=$(dirname $0)
FQNUNAME=$(which uname)
[ "$FQNUNAME" = "$0" ] && NEWPATH=$(echo $PATH | sed "s#$THISDIR:##") || NEWPATH="$PATH"

(export PATH=$NEWPATH && uname "$@" | sed 's#x86_64#amd64#g')
